version: '3.3'

services:
  app_api:
    network_mode: bridge
    container_name: app_api
    command: npm run dev
    hostname: app_api
    build:
      context: ./app
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    links:        
      - mongo:mongo
    expose:
      - 3001
      - 9229
    ports:
      - 3001:3001
      - 9229:9229
    environment:
      LOG_LEVEL: debug
      MONGODB_ENDPOINT: 'mongodb://mongo:27017/product'
      PORT: 3001
  
  client-api:
    network_mode: bridge
    container_name: client-api
    command: npm run dev
    hostname: client-api
    build:
      context: ./client-api
    volumes:
      - ./client-api:/client-api
      - ./client-api/node_modules:/client-api/node_modules
    links:        
      - app_api:app_api
    expose:
      - 3000
      - 9228
    ports:
      - 3000:3000
      - 9228:9228
    environment:
      PORT: 3000
      # API_URL: 'http://app_api/api'

  client-view:
    network_mode: bridge
    container_name: client-view
    command: npm run dev
    hostname: client-view
    build:
      context: ./client-view
    volumes:
      - ./client-view:/client-view
      - ./client-view/node_modules:/client-view/node_modules
    links:        
      - app_api:app_api
    expose:
      - 3002
      - 9227
    ports:
      - 3002:3002
      - 9227:9227

  mongo:
    network_mode: bridge
    container_name: mongo
    image: "mongo:3.4-jessie"
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
